version: 2
sources:
-   name: dbt_project_source
    database: NOVACOM
    schema: BRONZE
    tables:
    -   name: BIL_INVOICES
        columns:
        -   name: INVOICE_ID
        -   name: CUSTOMER_ID
        -   name: INVOICE_DATE
        -   name: DUE_DATE
        -   name: TOTAL_AMOUNT
        -   name: TAX_AMOUNT
        -   name: DISCOUNT_AMOUNT
        -   name: CURRENCY_CODE
        -   name: STATUS
        -   name: NOTE
        -   name: CREATED_AT
        -   name: UPDATED_AT
    -   name: BIL_INVOICE_ITEMS
        columns:
        -   name: ITEM_ID
        -   name: INVOICE_ID
        -   name: ITEM_CODE
        -   name: DESCRIPTION
        -   name: QUANTITY
        -   name: UNIT_PRICE
        -   name: TAX_RATE
        -   name: DISCOUNT_RATE
        -   name: LINE_TOTAL
        -   name: CREATED_AT
        -   name: UPDATED_AT
    -   name: BIL_PAYMENTS
        columns:
        -   name: PAYMENT_ID
        -   name: INVOICE_ID
        -   name: PAYMENT_DATE
        -   name: AMOUNT
        -   name: PAYMENT_METHOD
        -   name: TRANSACTION_ID
        -   name: CURRENCY_CODE
        -   name: NOTE
        -   name: CREATED_AT
        -   name: UPDATED_AT
    -   name: CRM_ACCOUNTS
        columns:
        -   name: ACCOUNT_ID
        -   name: CUSTOMER_ID
        -   name: ACCOUNT_TYPE
        -   name: CREATION_DATE
        -   name: STATUS
        -   name: CURRENCY_CODE
        -   name: BILLING_ADDRESS
        -   name: SHIPPING_ADDRESS
        -   name: ACCOUNT_BALANCE
        -   name: NOTE
        -   name: CREATED_AT
        -   name: UPDATED_AT
    -   name: CRM_CONTACTS
        columns:
        -   name: CONTACT_ID
        -   name: CUSTOMER_ID
        -   name: CONTACT_TYPE
        -   name: CONTACT_VALUE
        -   name: IS_PRIMARY
        -   name: CONTACT_LABEL
        -   name: NOTE
        -   name: CREATED_AT
        -   name: UPDATED_AT
    -   name: CRM_CUSTOMERS
        columns:
        -   name: CUSTOMER_ID
        -   name: FIRST_NAME
        -   name: MIDDLE_NAME
        -   name: LAST_NAME
        -   name: EMAIL
        -   name: PHONE
        -   name: DATE_OF_BIRTH
        -   name: ADDRESS_LINE1
        -   name: ADDRESS_LINE2
        -   name: CITY
        -   name: STATE
        -   name: ZIP_CODE
        -   name: COUNTRY
        -   name: CUSTOMER_SEGMENT
        -   name: CUSTOMER_TIER
        -   name: START_DATE
        -   name: STATUS
        -   name: NOTE
        -   name: CREATED_AT
        -   name: UPDATED_AT
    -   name: CRM_OPPORTUNITIES
        columns:
        -   name: OPPORTUNITY_ID
        -   name: ACCOUNT_ID
        -   name: STAGE
        -   name: PIPELINE_STAGE
        -   name: AMOUNT
        -   name: PROBABILITY_OF_CLOSE
        -   name: CLOSE_DATE
        -   name: ASSIGNED_SALES_REP
        -   name: NEXT_STEP
        -   name: NOTE
        -   name: CREATED_AT
        -   name: UPDATED_AT
    -   name: MKT_CAMPAIGNS
        columns:
        -   name: CAMPAIGN_ID
        -   name: NAME
        -   name: CAMPAIGN_TYPE
        -   name: OBJECTIVE
        -   name: TARGET_AUDIENCE
        -   name: CONVERSION_GOAL
        -   name: START_DATE
        -   name: END_DATE
        -   name: BUDGET
        -   name: CREATED_AT
        -   name: UPDATED_AT
    -   name: MKT_CAMPAIGN_TARGETS
        columns:
        -   name: TARGET_ID
        -   name: CAMPAIGN_ID
        -   name: CUSTOMER_ID
        -   name: ASSIGNED_DATE
        -   name: STATUS
        -   name: LAST_CONTACT_DATE
        -   name: CHANNEL
        -   name: RESPONSE_FLAG
        -   name: CREATED_AT
        -   name: UPDATED_AT
    -   name: NWK_EQUIPMENT
        columns:
        -   name: EQUIPMENT_ID
        -   name: ASSIGNMENT_ID
        -   name: EQUIPMENT_TYPE
        -   name: MODEL
        -   name: SERIAL_NUMBER
        -   name: FIRMWARE_VERSION
        -   name: IP_ADDRESS
        -   name: MAC_ADDRESS
        -   name: LOCATION
        -   name: STATUS
        -   name: LAST_MAINTENANCE_DATE
        -   name: CREATED_AT
        -   name: UPDATED_AT
    -   name: NWK_OUTAGES
        columns:
        -   name: OUTAGE_ID
        -   name: ASSIGNMENT_ID
        -   name: START_TIME
        -   name: END_TIME
        -   name: OUTAGE_TYPE
        -   name: REGION
        -   name: IMPACTED_CUSTOMERS_COUNT
        -   name: CAUSE
        -   name: RESOLUTION
        -   name: CREATED_AT
        -   name: UPDATED_AT
    -   name: NWK_USAGE
        columns:
        -   name: USAGE_ID
        -   name: ASSIGNMENT_ID
        -   name: USAGE_DATE
        -   name: USAGE_TYPE
        -   name: DATA_CONSUMED
        -   name: USAGE_UNIT
        -   name: USAGE_PEAK
        -   name: USAGE_COST
        -   name: CREATED_AT
        -   name: UPDATED_AT
    -   name: PRV_SERVICES
        columns:
        -   name: SERVICE_ID
        -   name: SERVICE_NAME
        -   name: SERVICE_TYPE
        -   name: DESCRIPTION
        -   name: MONTHLY_COST
        -   name: ACTIVE_FLAG
        -   name: PROVISIONING_TEAM
        -   name: CREATED_DATE
        -   name: UPDATED_AT
    -   name: PRV_SERVICE_ASSIGNMENTS
        columns:
        -   name: ASSIGNMENT_ID
        -   name: SERVICE_ID
        -   name: CUSTOMER_ID
        -   name: START_DATE
        -   name: END_DATE
        -   name: STATUS
        -   name: PROVISIONING_STATUS
        -   name: LAST_MODIFIED_DATE
        -   name: NOTE
        -   name: CREATED_AT
        -   name: UPDATED_AT
    -   name: SUP_KB_ARTICLES
        columns:
        -   name: KB_ARTICLE_ID
        -   name: TITLE
        -   name: CONTENT
        -   name: CATEGORY
        -   name: ARTICLE_AUTHOR
        -   name: VERSION_NUMBER
        -   name: EXTERNAL_LINK
        -   name: LAST_UPDATED
        -   name: CREATED_AT
        -   name: UPDATED_AT
    -   name: SUP_TICKETS
        columns:
        -   name: TICKET_ID
        -   name: CUSTOMER_ID
        -   name: CREATED_DATE
        -   name: STATUS
        -   name: PRIORITY
        -   name: SUBJECT
        -   name: DESCRIPTION
        -   name: CHANNEL_OF_CONTACT
        -   name: ASSIGNED_AGENT
        -   name: RESOLUTION_DATE
        -   name: CREATED_AT
        -   name: UPDATED_AT
    -   name: SUP_TICKET_NOTES
        columns:
        -   name: NOTE_ID
        -   name: TICKET_ID
        -   name: NOTE_DATE
        -   name: NOTE_AUTHOR
        -   name: NOTE_TEXT
        -   name: INTERNAL_FLAG
        -   name: CREATED_AT
        -   name: UPDATED_AT
